spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Quiz?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8"
    username: "zentao"
    password: "w123321"
  jpa:
    hibernate:
      ddl-auto: create
